// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using library_service_api.Data;

#nullable disable

namespace library_service_api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251206152752_InitialFullSeed")]
    partial class InitialFullSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("library_service_api.Models.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Jon Skeet"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Robert C. Martin"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Microsoft Docs Team"
                        });
                });

            modelBuilder.Entity("library_service_api.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AuthorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 1,
                            Description = "Deep dive into C#",
                            Title = "C# in Depth"
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = 2,
                            Description = "Code quality and best practices",
                            Title = "Clean Code"
                        },
                        new
                        {
                            Id = 3,
                            AuthorId = 3,
                            Description = "Learn ASP.NET Core fundamentals",
                            Title = "ASP.NET Core Guide"
                        });
                });

            modelBuilder.Entity("library_service_api.Models.BookCopy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AvailableCopies")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BookId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalCopies")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.ToTable("BookCopies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AvailableCopies = 4,
                            BookId = 1,
                            TotalCopies = 5
                        },
                        new
                        {
                            Id = 2,
                            AvailableCopies = 3,
                            BookId = 2,
                            TotalCopies = 3
                        },
                        new
                        {
                            Id = 3,
                            AvailableCopies = 4,
                            BookId = 3,
                            TotalCopies = 4
                        });
                });

            modelBuilder.Entity("library_service_api.Models.Loan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BookCopyId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("BorrowDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("MemberId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Returned")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ReturnedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BookCopyId")
                        .IsUnique();

                    b.HasIndex("MemberId");

                    b.ToTable("Loans");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BookCopyId = 1,
                            BorrowDate = new DateTime(2025, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DueDate = new DateTime(2025, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MemberId = 1,
                            Returned = false
                        });
                });

            modelBuilder.Entity("library_service_api.Models.Member", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Members");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "alice@example.com",
                            FullName = "Alice Walker"
                        },
                        new
                        {
                            Id = 2,
                            Email = "john@example.com",
                            FullName = "John Carter"
                        });
                });

            modelBuilder.Entity("library_service_api.Models.Book", b =>
                {
                    b.HasOne("library_service_api.Models.Author", "Author")
                        .WithMany("Books")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("library_service_api.Models.BookCopy", b =>
                {
                    b.HasOne("library_service_api.Models.Book", "Book")
                        .WithMany("BookCopies")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");
                });

            modelBuilder.Entity("library_service_api.Models.Loan", b =>
                {
                    b.HasOne("library_service_api.Models.BookCopy", "BookCopy")
                        .WithOne("Loan")
                        .HasForeignKey("library_service_api.Models.Loan", "BookCopyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("library_service_api.Models.Member", "Member")
                        .WithMany("Loans")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BookCopy");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("library_service_api.Models.Author", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("library_service_api.Models.Book", b =>
                {
                    b.Navigation("BookCopies");
                });

            modelBuilder.Entity("library_service_api.Models.BookCopy", b =>
                {
                    b.Navigation("Loan");
                });

            modelBuilder.Entity("library_service_api.Models.Member", b =>
                {
                    b.Navigation("Loans");
                });
#pragma warning restore 612, 618
        }
    }
}
